# Generated by Django 4.1.7 on 2023-04-10 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_contact_date_alter_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 10)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 10)),
        ),
    ]
