# Generated by Django 4.1.7 on 2023-03-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_staff_date_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('crimetype', models.CharField(max_length=30)),
                ('fir_date', models.DateField()),
                ('fir_station', models.CharField(max_length=30)),
                ('fir_copy', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.staff')),
            ],
            options={
                'db_table': 'case',
            },
        ),
    ]
